replicaCount: 1
fullnameOverride: pharma-ui
image:
  repository: 906615256368.dkr.ecr.us-east-1.amazonaws.com/pharma-ui
  tag: sha-c3fd9a6
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: pharma-qa
  host: qa.pharma.internal
  path: /
  pathType: Prefix
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
livenessProbe:
  path: /
  port: 80
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
configmap:
  API_BASE_URL: "/api"
  AUTH_BASE_URL: "/api/auth"
  ENV: qa
# Nginx requires writable directories even with readOnlyRootFilesystem: true
volumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: nginx-cache
    mountPath: /var/cache/nginx
  - name: nginx-run
    mountPath: /var/run
volumes:
  - name: tmp
    emptyDir: {}
  - name: nginx-cache
    emptyDir: {}
  - name: nginx-run
    emptyDir: {}
serviceAccount:
  create: true
  annotations: {}
  name: pharma-ui
