replicaCount: 1
fullnameOverride: api-gateway
image:
  repository: 906615256368.dkr.ecr.us-east-1.amazonaws.com/api-gateway
  tag: sha-c39ad23
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: pharma-dev
  host: ""
  path: /api
  pathType: Prefix
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
livenessProbe:
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  path: /actuator/health/readiness
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
configmap:
  SPRING_PROFILES_ACTIVE: dev
  LOG_LEVEL: DEBUG
  SERVER_PORT: "8080"
  # These match the fullnameOverride values of each service
  AUTH_SERVICE_URL: "http://auth-service:8081"
  DRUG_CATALOG_URL: "http://drug-catalog-service:8082"
  NOTIFICATION_URL: "http://notification-service:3000"
  QC_SERVICE_URL: "http://qc-service:8086"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
envFrom:
  - secretRef:
      name: db-credentials
  - secretRef:
      name: jwt-secret
volumeMounts:
  - name: tmp
    mountPath: /tmp
volumes:
  - name: tmp
    emptyDir: {}
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::873135413040:role/pharma-dev-eks-role
  name: api-gateway